### ISSUE TITLE
Animation not starting if requesting data from internet

### ISSUE THREAD

**Issue by Quamber** [EugeneTrapeznikov/ETActivityIndicatorView#1]
Hi, i am using ETActivityIndicatorView to be shown till the data has been loaded from internet the problem is that whenever i call the method to load data even after i have called activityIndicator's startAnimation function the indicator doesn't start animating and after the controller has downloaded all the data the indicator starts animating making it almost useless for me. IS there any solution to this problem?

**Comment by Quamber** [comment]
and i have checked that in start animation isAnimating while data is loading is NO and after data is loaded is YES

**Comment by rickwaalders** [comment]
Could it be that you are triggering it from a background thread instead of the main (UI) thread? I had similar problems and found out I was starting the animation from one of my background threads...

**Comment by Quamber** [comment]
yes i have resolved that i moved all the commands to a function and called it using NSThread.

**Comment by EugeneTrapeznikov** [comment]
The animation wasn't started in UI thread. Issue resolved.
